"""add safe nullable

Revision ID: 06a6b14e4591
Revises: 8b6af23ddaf8
Create Date: 2021-03-31 17:21:40.355427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a6b14e4591'
down_revision = '8b6af23ddaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masalah', 'foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masalah', sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
