"""fixing name of relatioship between ruangan and masalah

Revision ID: 10f8e45d1a4d
Revises: 3ca94378d0e9
Create Date: 2021-02-25 20:14:34.647105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f8e45d1a4d'
down_revision = '3ca94378d0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
