"""fix id in Pegawai

Revision ID: 174f5e1a1897
Revises: 4f37c9caa41c
Create Date: 2021-03-04 13:32:20.777470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174f5e1a1897'
down_revision = '4f37c9caa41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
