"""adding onupdate user

Revision ID: 21f910324bf3
Revises: ea4e035d63b8
Create Date: 2021-01-26 12:04:30.352696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f910324bf3'
down_revision = 'ea4e035d63b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
