"""add kondisi_pasca to tindakan

Revision ID: 286222c0d9c8
Revises: f125e9b16b3a
Create Date: 2021-04-06 08:11:57.296495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286222c0d9c8'
down_revision = 'f125e9b16b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tindakan', sa.Column('kondisi_pasca', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tindakan', 'kondisi_pasca')
    # ### end Alembic commands ###
