"""add foto_selesai masalah

Revision ID: 2a76bcbc8a70
Revises: 286222c0d9c8
Create Date: 2021-04-20 14:02:28.627351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a76bcbc8a70'
down_revision = '286222c0d9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masalah', sa.Column('foto_selesai', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masalah', 'foto_selesai')
    # ### end Alembic commands ###
