"""add jenis relationship to sarana

Revision ID: 3ca94378d0e9
Revises: b9781b0661e9
Create Date: 2021-02-25 19:17:55.274892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca94378d0e9'
down_revision = 'b9781b0661e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('masalah_id_level_1_fkey', 'masalah', type_='foreignkey')
    op.drop_constraint('masalah_id_level_3_fkey', 'masalah', type_='foreignkey')
    op.drop_constraint('masalah_id_level_2_fkey', 'masalah', type_='foreignkey')
    op.drop_column('masalah', 'id_level_2')
    op.drop_column('masalah', 'id_level_1')
    op.drop_column('masalah', 'id_level_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masalah', sa.Column('id_level_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('masalah', sa.Column('id_level_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('masalah', sa.Column('id_level_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('masalah_id_level_2_fkey', 'masalah', 'users', ['id_level_2'], ['id'])
    op.create_foreign_key('masalah_id_level_3_fkey', 'masalah', 'users', ['id_level_3'], ['id'])
    op.create_foreign_key('masalah_id_level_1_fkey', 'masalah', 'users', ['id_level_1'], ['id'])
    # ### end Alembic commands ###
