"""delete done column in jenis_sarana

Revision ID: 558faae51090
Revises: 174f5e1a1897
Create Date: 2021-03-10 19:51:11.825428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '558faae51090'
down_revision = '174f5e1a1897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jenis_sarana', 'done_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jenis_sarana', sa.Column('done_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
