"""adding cud_date to Item

Revision ID: 6dbd7e25def7
Revises: 21f910324bf3
Create Date: 2021-01-27 13:29:30.357283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbd7e25def7'
down_revision = '21f910324bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'update_at')
    op.drop_column('items', 'deleted_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
