"""add foto to sarana

Revision ID: 8b6af23ddaf8
Revises: 512e99c285ed
Create Date: 2021-03-15 16:51:30.328516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6af23ddaf8'
down_revision = '512e99c285ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
