"""init table

Revision ID: 9533f0619edf
Revises: 2451341c6f05
Create Date: 2021-02-18 11:46:08.037565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9533f0619edf'
down_revision = '2451341c6f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instalasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instalasi_id'), 'instalasi', ['id'], unique=False)
    op.create_table('jenis_sarana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_sarana_id'), 'jenis_sarana', ['id'], unique=False)
    op.create_table('kategori_masalah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategori_masalah_id'), 'kategori_masalah', ['id'], unique=False)
    op.create_table('kategori_tindakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategori_tindakan_id'), 'kategori_tindakan', ['id'], unique=False)
    op.create_table('pegawai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=60), nullable=True),
    sa.Column('nama_panggilan', sa.String(length=60), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.DateTime(), nullable=True),
    sa.Column('no_hp', sa.String(length=16), nullable=True),
    sa.Column('no_wa', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pegawai_id'), 'pegawai', ['id'], unique=False)
    op.create_table('ruangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('id_instalasi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_instalasi'], ['instalasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruangan_id'), 'ruangan', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id_pegawai', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pegawai'], ['pegawai.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sarana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=90), nullable=True),
    sa.Column('berat', sa.String(length=30), nullable=True),
    sa.Column('panjang', sa.String(length=30), nullable=True),
    sa.Column('lebar', sa.String(length=30), nullable=True),
    sa.Column('tinggi', sa.String(length=30), nullable=True),
    sa.Column('id_ruangan', sa.Integer(), nullable=True),
    sa.Column('id_jenis', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_jenis'], ['jenis_sarana.id'], ),
    sa.ForeignKeyConstraint(['id_ruangan'], ['ruangan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sarana_id'), 'sarana', ['id'], unique=False)
    op.create_table('masalah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_kategori_masalah', sa.Integer(), nullable=True),
    sa.Column('id_ruangan', sa.Integer(), nullable=True),
    sa.Column('id_sarana', sa.Integer(), nullable=True),
    sa.Column('id_level_1', sa.Integer(), nullable=True),
    sa.Column('id_level_2', sa.Integer(), nullable=True),
    sa.Column('id_level_3', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori_masalah'], ['kategori_masalah.id'], ),
    sa.ForeignKeyConstraint(['id_level_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_level_2'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_level_3'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_ruangan'], ['ruangan.id'], ),
    sa.ForeignKeyConstraint(['id_sarana'], ['sarana.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masalah_id'), 'masalah', ['id'], unique=False)
    op.create_table('tindakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kondisi_awal', sa.String(), nullable=True),
    sa.Column('tindakan', sa.String(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.Column('id_sarana', sa.Integer(), nullable=True),
    sa.Column('id_ruangan', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori_tindakan.id'], ),
    sa.ForeignKeyConstraint(['id_ruangan'], ['ruangan.id'], ),
    sa.ForeignKeyConstraint(['id_sarana'], ['sarana.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tindakan_id'), 'tindakan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tindakan_id'), table_name='tindakan')
    op.drop_table('tindakan')
    op.drop_index(op.f('ix_masalah_id'), table_name='masalah')
    op.drop_table('masalah')
    op.drop_index(op.f('ix_sarana_id'), table_name='sarana')
    op.drop_table('sarana')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ruangan_id'), table_name='ruangan')
    op.drop_table('ruangan')
    op.drop_index(op.f('ix_pegawai_id'), table_name='pegawai')
    op.drop_table('pegawai')
    op.drop_index(op.f('ix_kategori_tindakan_id'), table_name='kategori_tindakan')
    op.drop_table('kategori_tindakan')
    op.drop_index(op.f('ix_kategori_masalah_id'), table_name='kategori_masalah')
    op.drop_table('kategori_masalah')
    op.drop_index(op.f('ix_jenis_sarana_id'), table_name='jenis_sarana')
    op.drop_table('jenis_sarana')
    op.drop_index(op.f('ix_instalasi_id'), table_name='instalasi')
    op.drop_table('instalasi')
    # ### end Alembic commands ###
