"""linking masalah and tindakan

Revision ID: a0186cbc80f3
Revises: 10f8e45d1a4d
Create Date: 2021-03-01 13:18:36.550399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0186cbc80f3'
down_revision = '10f8e45d1a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tindakan', sa.Column('id_masalah', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tindakan', 'masalah', ['id_masalah'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tindakan', type_='foreignkey')
    op.drop_column('tindakan', 'id_masalah')
    # ### end Alembic commands ###
