"""login response correction

Revision ID: a4c454deb6bb
Revises: b42422609ece
Create Date: 2021-03-11 08:19:24.756828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c454deb6bb'
down_revision = 'b42422609ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jenis_sarana', 'done_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jenis_sarana', sa.Column('done_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
