"""add disposition label to masalah

Revision ID: caacc7202357
Revises: 1e476d25c36c
Create Date: 2021-03-31 18:10:19.283143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caacc7202357'
down_revision = '1e476d25c36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masalah', sa.Column('id_level_1', sa.Integer(), nullable=True))
    op.add_column('masalah', sa.Column('id_level_2', sa.Integer(), nullable=True))
    op.add_column('masalah', sa.Column('id_level_3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masalah', 'id_level_3')
    op.drop_column('masalah', 'id_level_2')
    op.drop_column('masalah', 'id_level_1')
    # ### end Alembic commands ###
