"""remove disposisi from user

Revision ID: d479c23c3e13
Revises: caacc7202357
Create Date: 2021-03-31 19:43:03.351781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd479c23c3e13'
down_revision = 'caacc7202357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
