"""adding cud_date

Revision ID: ea4e035d63b8
Revises: 2cd9645b6494
Create Date: 2021-01-26 12:03:33.100024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4e035d63b8'
down_revision = '2cd9645b6494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
