"""add id_user to tindakan

Revision ID: f125e9b16b3a
Revises: c7c4f8b5b369
Create Date: 2021-04-05 09:51:45.043823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f125e9b16b3a'
down_revision = 'c7c4f8b5b369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tindakan', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tindakan', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tindakan', type_='foreignkey')
    op.drop_column('tindakan', 'id_user')
    # ### end Alembic commands ###
